project:
  type: book

book:
  title: "Biostatistics, Epidemiology and Data Science"
  author: "André van Zyl (M.P.H.)"
  date: today
  page-navigation: true
  cover-image: cover.png
  chapters:
        - index.qmd
        - chapters/intro.qmd
        - part: chapters/part01/biostatistics.qmd
          chapters:
                - chapters/part01/basics_of_biostatistics.qmd
                - chapters/part01/summary_measures.qmd
                - chapters/part01/chapter02.qmd
        - part: chapters/part02/chapter00.qmd
          chapters:      
                - chapters/part02/chapter01.qmd
                - chapters/part02/chapter02.qmd
        - chapters/summary.qmd
section-titles: true


filters:
  - section-bibliographies
bibliography: chapters/references.bib
reference-section-title: References
citeproc: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png



